# frozen_string_literal: true
# Generated by listennotes/devtools/api-sdks/sync.py ruby. Do not edit.

module PodcastApi
  module ApiMethods
    def search(**kwargs)
      request_api('GET', '/search',
                  ['q', 'sort_by_date', 'type', 'offset', 'len_min', 'len_max', 'episode_count_min', 'episode_count_max', 'update_freq_min', 'update_freq_max', 'genre_ids', 'published_before', 'published_after', 'only_in', 'language', 'region', 'ocid', 'ncid', 'safe_mode', 'unique_podcasts', 'interviews_only', 'sponsored_only', 'page_size'], kwargs)
    end

    def typeahead(**kwargs)
      request_api('GET', '/typeahead',
                  ['q', 'show_podcasts', 'show_genres', 'safe_mode'], kwargs)
    end

    def search_episode_titles(**kwargs)
      request_api('GET', '/search_episode_titles',
                  ['q', 'podcast_id', 'podcast_id_type'], kwargs)
    end

    def spellcheck(**kwargs)
      request_api('GET', '/spellcheck',
                  ['q'], kwargs)
    end

    def fetch_related_searches(**kwargs)
      request_api('GET', '/related_searches',
                  ['q'], kwargs)
    end

    def fetch_trending_searches(**kwargs)
      request_api('GET', '/trending_searches',
                  [], kwargs)
    end

    def fetch_best_podcasts(**kwargs)
      request_api('GET', '/best_podcasts',
                  ['genre_id', 'page', 'region', 'publisher_region', 'language', 'sort', 'safe_mode'], kwargs)
    end

    def fetch_podcast_by_id(**kwargs)
      request_api('GET', '/podcasts/{id}',
                  ['next_episode_pub_date', 'sort'], kwargs)
    end

    def delete_podcast(**kwargs)
      request_api('DELETE', '/podcasts/{id}',
                  ['reason'], kwargs)
    end

    def fetch_episode_by_id(**kwargs)
      request_api('GET', '/episodes/{id}',
                  ['show_transcript'], kwargs)
    end

    def batch_fetch_episodes(**kwargs)
      request_api('POST', '/episodes',
                  [], kwargs)
    end

    def batch_fetch_podcasts(**kwargs)
      request_api('POST', '/podcasts',
                  [], kwargs)
    end

    def fetch_curated_podcasts_list_by_id(**kwargs)
      request_api('GET', '/curated_podcasts/{id}',
                  [], kwargs)
    end

    def fetch_podcast_genres(**kwargs)
      request_api('GET', '/genres',
                  ['top_level_only'], kwargs)
    end

    def fetch_podcast_regions(**kwargs)
      request_api('GET', '/regions',
                  [], kwargs)
    end

    def fetch_podcast_languages(**kwargs)
      request_api('GET', '/languages',
                  [], kwargs)
    end

    def just_listen(**kwargs)
      request_api('GET', '/just_listen',
                  [], kwargs)
    end

    def fetch_curated_podcasts_lists(**kwargs)
      request_api('GET', '/curated_podcasts',
                  ['page'], kwargs)
    end

    def fetch_recommendations_for_podcast(**kwargs)
      request_api('GET', '/podcasts/{id}/recommendations',
                  ['safe_mode'], kwargs)
    end

    def fetch_recommendations_for_episode(**kwargs)
      request_api('GET', '/episodes/{id}/recommendations',
                  ['safe_mode'], kwargs)
    end

    def submit_podcast(**kwargs)
      request_api('POST', '/podcasts/submit',
                  [], kwargs)
    end

    def fetch_playlist_by_id(**kwargs)
      request_api('GET', '/playlists/{id}',
                  ['type', 'last_timestamp_ms', 'sort'], kwargs)
    end

    def fetch_my_playlists(**kwargs)
      request_api('GET', '/playlists',
                  ['sort', 'page'], kwargs)
    end

    def fetch_audience_for_podcast(**kwargs)
      request_api('GET', '/podcasts/{id}/audience',
                  [], kwargs)
    end

    def fetch_podcasts_by_domain(**kwargs)
      request_api('GET', '/podcasts/domains/{domain_name}',
                  ['page'], kwargs)
    end

    def create_playlist(**kwargs)
      request_api('POST', '/playlists',
                  [], kwargs)
    end

    def update_playlist(**kwargs)
      request_api('PUT', '/playlists/{id}',
                  [], kwargs)
    end

    def add_playlist_item(**kwargs)
      request_api('POST', '/playlists/{id}/items',
                  [], kwargs)
    end

    def delete_playlist_item(**kwargs)
      request_api('DELETE', '/playlists/{id}/items/{item_id}',
                  [], kwargs)
    end

    def update_playlist_item_notes(**kwargs)
      request_api('PUT', '/playlists/{id}/items/{item_id}',
                  [], kwargs)
    end

  end
end
